name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21, 1.22, 1.23]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build ./...

    - name: Check formatting
      run: |
        if [ "$(gofmt -l .)" != "" ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          gofmt -l .
          exit 1
        fi

    - name: Test RLNC Network Example
      run: |
        cd examples/rlnc-network
        go build
        ./test.sh

    - name: Test Reed-Solomon Network Example
      run: |
        cd examples/rs-network
        go build
        ./test.sh

  shadow-simulation:
    name: Shadow Network Simulation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip3 install networkx pyyaml

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.89.0

    - name: Install Shadow simulator
      run: |
        # Install Shadow dependencies
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          findutils \
          libclang-dev \
          libc-dbg \
          libglib2.0-0 \
          libglib2.0-dev \
          make \
          netbase \
          python3 \
          python3-networkx \
          xz-utils

        # Build and install Shadow v3.2.0 from source
        git clone --depth 1 --branch v3.2.0 https://github.com/shadow/shadow.git shadow-simulator
        cd shadow-simulator
        git checkout v3.2.0
        ./setup build --clean
        ./setup install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Download Go dependencies
      run: go mod download

    - name: Run Shadow simulation tests
      run: |
        cd shadow
        make all-topologies
      timeout-minutes: 60

    - name: Upload Shadow logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shadow-logs
        path: shadow/shadow.data/

  protocol-comparison:
    name: Protocol Comparison Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip3 install networkx pyyaml matplotlib numpy

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.89.0

    - name: Install Shadow simulator
      run: |
        # Install Shadow dependencies
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          findutils \
          libclang-dev \
          libc-dbg \
          libglib2.0-0 \
          libglib2.0-dev \
          make \
          netbase \
          python3 \
          python3-networkx \
          xz-utils

        # Build and install Shadow v3.2.0 from source
        git clone --depth 1 --branch v3.2.0 https://github.com/shadow/shadow.git shadow-simulator
        cd shadow-simulator
        git checkout v3.2.0
        ./setup build --clean
        ./setup install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Download Go dependencies
      run: go mod download

    - name: Run protocol comparison script
      run: |
        cd shadow
        python3 compare_protocols.py --msg-size 512 --num-chunks 8 --node-count 5 --msg-count 1
      timeout-minutes: 30

    - name: Upload comparison plot
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: protocol-comparison-plot
        path: shadow/protocol_comparison_cdf.png

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: protocol-comparison-logs
        path: |
          shadow/gossipsub/shadow.data/
          shadow/rs/shadow.data/
          shadow/rlnc/shadow.data/

  benchmark-shadow-verifier:
    name: Benchmark and Shadow Verifier Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip3 install networkx pyyaml

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.89.0

    - name: Install Shadow simulator
      run: |
        # Install Shadow dependencies
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          findutils \
          libclang-dev \
          libc-dbg \
          libglib2.0-0 \
          libglib2.0-dev \
          make \
          netbase \
          python3 \
          python3-networkx \
          xz-utils

        # Build and install Shadow v3.2.0 from source
        git clone --depth 1 --branch v3.2.0 https://github.com/shadow/shadow.git shadow-simulator
        cd shadow-simulator
        git checkout v3.2.0
        ./setup build --clean
        ./setup install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Download Go dependencies
      run: go mod download

    - name: Build benchmark-pedersen tool
      run: go build -o benchmark-pedersen ./cmd/benchmark-pedersen

    - name: Run benchmark (fast mode for CI)
      run: ./benchmark-pedersen -chunk-size 32 -num-chunks 8 -iterations 10 -output pedersen_benchmark.json

    - name: Verify benchmark output
      run: |
        if [ ! -f pedersen_benchmark.json ]; then
          echo "Error: Benchmark file not created"
          exit 1
        fi
        # Check that the JSON is valid and has expected structure
        python3 -c "import json; data = json.load(open('pedersen_benchmark.json')); assert data['num_chunks'] == 8; assert data['elements_per_chunk'] == 1; print(f'Benchmark result for {data[\"num_chunks\"]} chunks with {data[\"elements_per_chunk\"]} elements loaded successfully')"

    - name: Run RLNC simulation without verifier (baseline)
      run: |
        cd shadow/rlnc
        make all NODE_COUNT=5 MSG_SIZE=256 MSG_COUNT=1 NUM_CHUNKS=8
      timeout-minutes: 10

    - name: Run RLNC simulation with ShadowPedersenVerifier
      run: |
        BENCHMARK_PATH=$(realpath pedersen_benchmark.json)
        cd shadow/rlnc
        make clean
        make all BENCHMARK_FILE=$BENCHMARK_PATH NODE_COUNT=5 MSG_SIZE=256 MSG_COUNT=1 NUM_CHUNKS=8
      timeout-minutes: 10

    - name: Verify simulation success
      run: |
        cd shadow/rlnc
        python3 ../test_results.py 5 1 rlnc

    - name: Upload benchmark file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pedersen-benchmark
        path: pedersen_benchmark.json

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-shadow-logs
        path: shadow/rlnc/shadow.data/
